### ISSUE TITLE
deluxe version not recognized

### ISSUE THREAD

**Issue by adeline-ozzie** [Roshy10/taylors-version#103]
hi there!!

i just want to say that i truly appreciate all you’re doing and i can’t imagine the amount of work that gets put into this. however, i did run into an issue today when trying to taylor’s version-ify my playlists. for whatever reason, it seems that i all these years ago that i added these songs to my playlists, i added them from the deluxe version of 1989. the website only recognized the few that i had added from the standard version, and none from the deluxe. is there a way this could be fixed? if i have to do it manually, i don’t mind, but your website makes things so much easier for me! thank you!

**Comment by Roshy10** [comment]
thanks for the report, this should be fixed now. please re open the issue if it's not
