### ISSUE TITLE
Mine - Pop Mix (stolen version) not recognized

### ISSUE THREAD

**Issue by mxlanced** [Roshy10/taylors-version#109]
Hi there! Really like what you're doing!

App works perfectly fine but it doesn't pick up on "Mine - Pop Mix" from the stolen Speak Now/Deluxe (URIs: `spotify:track:0OAHsZ8vrS2NKom3cvfJQD` for standard SN stolen and `spotify:track:0GxW5K0qzrq7L1jwSY5OmY` for deluxe stolen version) and does not automatically replace these with Mine (TV) (URI: 
`spotify:track:7G0gBu6nLdhFDPRLc0HdDG`).

Keep up the good work and the service to Swifties worldwide!

**Comment by Roshy10** [comment]
Hi, thanks for raising an issue!

I intentionally chose not to replace (re)mixes as they're kind of different songs, and I'd rather err on the side of caution to not mess up anyone's playlists.

I may revisit this option in future, but for now you'll have to manually swap those ones out.

Roshan
