### ISSUE TITLE
update wildest dreams (taylor's version)

### ISSUE THREAD

**Issue by mirrorballing** [Roshy10/taylors-version#39]
Hey, I came across your website which replaces the stolen(old) version of taylor swift's songs with her newly re-recorded ones.. First i want to thank you for this amazing work,.. So taylor dropped her new version of wildest dreams today so can you please update it with wildest dreams (taylor's version) so that everone can replace the old one with new one!

I really hope your site gets updated soon!! Thank you once again for your cooperation and the great work without which it would be SO difficult for everyone to replace those songs in our playlists one by one!!

**Comment by Roshy10** [comment]
Thanks, I've only just seen this but the site has just been updated 🙂
